---
# tasks file for mapr-fileserver

- name: install mapr-fileserver
  become: yes
  become_user: root
  yum: name='{{item}}' state=present
  with_items:
    - mapr-fileserver
  when: ansible_distribution in ('CentOS', 'RedHat', 'Amazon')
  environment: proxy_env
